Abstract backend
Tfloow/UCLouvainDown pull request #5
Opened 2024-01-22 14:40 UTC by VermeulenWouter

2024-01-22 19:34 UTC, Tfloow commented
Okay, I've started merging the master branch into your branch.
The first loading really takes a lot of time but then everything is pretty smooth !

I am currently working on handling the new JSON strucutre for other dependecies

2024-01-23 08:24 UTC, Tfloow requested changes

2024-01-23 08:24 UTC, Tfloow commented on services.json
Je ne comprends pas trop l'avantage de passer à des "dictionnaire imbriqué" à une liste de dictionnaire. J'ai l'impression que ça va être plus compliqué à lire les différents service (et surtout que j'ai poussé le module JSONutility assez loin donc ça risque de tout casser avec la nouvelle structure)

2024-01-23 08:24 UTC, Tfloow commented on fastapi_custom.py
Génial !

2024-01-23 08:24 UTC, Tfloow commented on app.py
Faut voir comment la nouvelle interface des JSON s'intègre avec ce code et les autres bouts de code

2024-01-23 08:24 UTC, Tfloow commented on models.py
Simplifie le backend mais j'avais des erreurs sur python avec

2024-01-23 19:53 UTC, Tfloow reviewed
Good job. I think we should aim for the API and webhook first because they don't overlap with the current capabilities of the app (so less hassle to merge it ahha)

2024-01-23 19:53 UTC, Tfloow commented on utilities.py
omg les password

2024-01-23 19:53 UTC, Tfloow commented on models.py
En vrai le plus important (et ce qui causera le moins de problème avec le site c'est l'api et le webhook je pense)

2024-01-24 21:11 UTC, VermeulenWouter commented
Even though webhook update / deletion is not yet possible, I believe it is a good idea to merge into master.

_Note: for some reason when importing dataReport I keep getting errors. But I saw some changes in the master branch which I believe would resolve those issues. _

2024-01-25 12:02 UTC, merged